// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/axidex/depscan/internal/remediate (interfaces: VersionLister)
//
// Generated by this command:
//
//	mockgen -destination internal/remediate/mock_versionlister_test.go -package remediate github.com/axidex/depscan/internal/remediate VersionLister
//

// Package remediate is a generated GoMock package.
package remediate

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockVersionLister is a mock of VersionLister interface.
type MockVersionLister struct {
	ctrl     *gomock.Controller
	recorder *MockVersionListerMockRecorder
	isgomock struct{}
}

// MockVersionListerMockRecorder is the mock recorder for MockVersionLister.
type MockVersionListerMockRecorder struct {
	mock *MockVersionLister
}

// NewMockVersionLister creates a new mock instance.
func NewMockVersionLister(ctrl *gomock.Controller) *MockVersionLister {
	mock := &MockVersionLister{ctrl: ctrl}
	mock.recorder = &MockVersionListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersionLister) EXPECT() *MockVersionListerMockRecorder {
	return m.recorder
}

// Versions mocks base method.
func (m *MockVersionLister) Versions(ctx context.Context, group, artifact string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Versions", ctx, group, artifact)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Versions indicates an expected call of Versions.
func (mr *MockVersionListerMockRecorder) Versions(ctx, group, artifact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Versions", reflect.TypeOf((*MockVersionLister)(nil).Versions), ctx, group, artifact)
}
