// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/axidex/craftnovate/internal/worker (interfaces: Platform)
//
// Generated by this command:
//
//	mockgen -destination internal/worker/mock_platform_test.go -package worker github.com/axidex/craftnovate/internal/worker Platform
//

// Package worker is a generated GoMock package.
package worker

import (
	context "context"
	reflect "reflect"

	sourcecraft "github.com/axidex/craftnovate/internal/sourcecraft"
	gomock "go.uber.org/mock/gomock"
)

// MockPlatform is a mock of Platform interface.
type MockPlatform struct {
	ctrl     *gomock.Controller
	recorder *MockPlatformMockRecorder
	isgomock struct{}
}

// MockPlatformMockRecorder is the mock recorder for MockPlatform.
type MockPlatformMockRecorder struct {
	mock *MockPlatform
}

// NewMockPlatform creates a new mock instance.
func NewMockPlatform(ctrl *gomock.Controller) *MockPlatform {
	mock := &MockPlatform{ctrl: ctrl}
	mock.recorder = &MockPlatformMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlatform) EXPECT() *MockPlatformMockRecorder {
	return m.recorder
}

// CreatePullRequest mocks base method.
func (m *MockPlatform) CreatePullRequest(ctx context.Context, repoID string, body sourcecraft.CreatePullRequestBody) (*sourcecraft.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePullRequest", ctx, repoID, body)
	ret0, _ := ret[0].(*sourcecraft.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePullRequest indicates an expected call of CreatePullRequest.
func (mr *MockPlatformMockRecorder) CreatePullRequest(ctx, repoID, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePullRequest", reflect.TypeOf((*MockPlatform)(nil).CreatePullRequest), ctx, repoID, body)
}

// ListMyPulls mocks base method.
func (m *MockPlatform) ListMyPulls(ctx context.Context) ([]sourcecraft.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMyPulls", ctx)
	ret0, _ := ret[0].([]sourcecraft.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMyPulls indicates an expected call of ListMyPulls.
func (mr *MockPlatformMockRecorder) ListMyPulls(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMyPulls", reflect.TypeOf((*MockPlatform)(nil).ListMyPulls), ctx)
}

// SetLabels mocks base method.
func (m *MockPlatform) SetLabels(ctx context.Context, prID string, slugs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLabels", ctx, prID, slugs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLabels indicates an expected call of SetLabels.
func (mr *MockPlatformMockRecorder) SetLabels(ctx, prID, slugs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLabels", reflect.TypeOf((*MockPlatform)(nil).SetLabels), ctx, prID, slugs)
}
